version: "3.7"

services:
  dockerbot:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: dockerbot-test
    network_mode: host
    cap_add:
      - NET_ADMIN
    privileged: true
    restart: always
    environment:
      - API_KEY=
      - ALLOWED_IDS=
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /home/adam/test-volume:/opt/config
