version: "3.7"

services:
  dockerbot:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: dockerbot
    network_mode: host
    cap_add:
      - NET_ADMIN
    privileged: true
    restart: always
    environment:
      - API_KEY=1351394252:AAEJ3Ixoi04an714cbswFQgDTnWEdOG_mfc
      - ALLOWED_IDS=293329174
      - USER_ID=
      - USER_KEY=
      - KIDS_NUM=
      - PYTHONIOENCODING=
      - LANG=      
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./Botvid19.env:/opt/Botvid19.env
